sudo: false
dist: xenial
language: python
python: "2.7"
before_install: pip install coveralls
install:
  - pip install Django==${DJANGO}
  - travis_retry pip install -r tests/requirements.txt
script: make test
env:
  - DJANGO=1.10.*
  - DJANGO=1.11.23
after_success: coveralls
